- name: Setup roboshop project
  hosts: FRONTEND
  become: yes
  roles:
    - name: Load Frontend Roles
      role: frontend




#- name: Setup roboshop project
#  hosts: MONGODB
#  roles:
#   - name: Load frontend Role
#      role: mongodb

